### ISSUE TITLE
Can't delete the currently active theme

### ISSUE THREAD

**Issue by cristacheda** [flurinduerst/WPDistillery#42] opened 2017-02-03 11:07 UTC
I'm running Vagrant 1.9.1 on Windows 10 and trying to start the box, everything goes well until the script tries to delete the currently active theme and gives this error:

==> default: Deleted 'twentyfifteen' theme.
==> default: Success: Deleted 1 of 1 themes.
==> default: Deleted 'twentysixteen' theme.
==> default: Success: Deleted 1 of 1 themes.
==> default: Warning: Can't delete the currently active theme: twentyseventeen
==> default: Error: No themes deleted.
==> default: »»» aborting WPDistillery setup!

**Comment by flurinduerst** [comment] 2017-02-03 12:33
Is the `twentyseventeen` available in your WordPress installation? Please add your config.yml so I can troubleshoot.

Note: You don't have to abort the script after this error, I assume you've had the option to continue anyway, right?

**Comment by cristacheda** [comment] 2017-02-07 20:03
It was a fresh installation. I didn't get any prompts, the script would automatically exit after the error.
```
# Configuration for WPDistillery executed by setup.sh
#
# Author: Flurin Dürst
# URL: https://wpdistillery.org
#
# For detailed instructions on this file read the config.yml-documentation at
# https://wpdistillery.org/documentation/config-yml-documentation/
#
# File Version: 1.6.4


# INSTALLATION
#################################################################

# WordPress folder
wpfolder: public

# WordPress version
wpversion: latest

# language/timezone
wplocale: ro_RO
timezone: "Europe/Bucharest"

# admin user settings
admin:
  user: dragos.cristache
  password: **********
  email: dragos@cristache.net
  first_name: "Dragos"
  last_name: "Cristache"

# scotch box db access
db:
  name: scotchbox
  user: root
  pass: root
  prefix: wp_

# SETTINGS
#################################################################

wpsettings:
  url: geoproject.dev
  title: GeoProject
  description: Studii geotehnice, geologice și foraje puțuri
  permalink_structure: "/%postname%/"
  thumbnail_width: 150
  thumbnail_height: 150
  medium_width: 300
  medium_height: 300
  large_width: 1024
  large_height: 1024
  # use page as frontpage
  page_on_front: true
    frontpage_name: Example Front Page
  # automatic conversion of smilies
  convert_smilies: false

# THEME
#################################################################

# theme to install, choose new name in 'rename' or leave empty
theme:
  name: WPSeed
  rename: ""
  url: "https://github.com/flurinduerst/WPSeed/archive/master.zip"

# PLUGINS
#################################################################

# plugins to install & activate
plugins_active:
  - wordpress-seo
  - contact-form-7
  - yoast-seo-acf-analysis
  - ajax-thumbnail-rebuild

# plugins to install
plugins_inactive:
  - better-search-replace
  - sucuri-scanner
  - backwpup

# WPDISTILLERY SETUP
####################################################################
# if you don't want the setup to run all tasks, set them to false

setup:
  wp: true
  settings: true
  theme: true
  plugins: true
  cleanup: true
    comment: true
    posts: true
    files: true
    themes: true
```

**Comment by flurinduerst** [comment] 2017-02-07 20:06
thanks, I will have a look at this.

btw. 
- i edited your post, because you've shown your password - don't do this :)
- you can use upload file or add \``` before and after code to set it into a code block, did that too :)

**Comment by cristacheda** [comment] 2017-02-07 20:09
Thank you! I'm kinda sorta new to GitHub.

**Comment by flurinduerst** [comment] 2017-02-08 11:16
The problem is that wpdistillery (WP-CLI) can't delete the currently active theme, it looks like the WPSeed theme couldn't be installed/activated before deleting the default themes. Did you get any warnings/error before that? 

Your problem can be fixed for now by skipping the theme-cleanup part of the setup by setting `cleanup:themes` to `false` like so:

```
setup:
  wp: true
  settings: true
  theme: true
  plugins: true
  cleanup: true
    comment: true
    posts: true
    files: true
    themes: false
```

**Comment by cristacheda** [comment] 2017-02-08 20:56
No warnings/error before. I will set cleanup:themes to false, I don't mind having the latest default Wordpress theme installed just as a backup in case something goes bad.

**Comment by flurinduerst** [comment] 2017-04-11 11:40
will be fixed withing the bugfix for https://github.com/flurinduerst/WPDistillery/issues/47. 

Thanks

**Closed as completed by flurinduerst** 2017-04-11 11:40 UTC
