### ISSUE TITLE
Cannot connect after setting up with default configuration

### ISSUE THREAD

**Issue by johnpitchko** [flurinduerst/WPDistillery#30] opened 2016-10-27 18:54 UTC
Installed WPDistillery in a fresh directory following all instructions posted. Observed a few issues during set up:
1. Connection refused when installing wordpress

```
»»» installing wordpress...
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 1025 (Errno::ECONNREFUSED)
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `open'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `tcp_socket'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:551:in `block in do_start'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `call'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:550:in `do_start'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:238:in `deliver'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/bin/catchmail:71:in `<top (required)>'
    from /home/vagrant/.rbenv/versions/2.2.2/bin/catchmail:23:in `load'
    from /home/vagrant/.rbenv/versions/2.2.2/bin/catchmail:23:in `<main>'
Success: WordPress installed successfully.
Success: Updated user 1.
```
1. Error during theme installation

```
»»» installing/activating WPSeed...
mv: cannot stat ‘wp-content/themes/WPSeed-master’: No such file or directory
Do you want to continue anyway? (y/n) y
»»» continuing WPDistillery setup...
```

No other error messages detected.

When attempting to load wpdistillery.dev, received the following Google error: `ERR_CONNECTION_TIMED_OUT`

**Comment by ShaneShipston** [comment] 2016-10-27 20:12
In regards to the first error you received it is trying to send out the welcome email for the admin account that was created. You can either add `--skip-email` to the end of line 79 in the setup.sh or activate mail catcher before installation. You can refer to https://box.scotch.io/ for running mail catcher.

**Comment by realnerdo** [comment] 2016-11-04 20:10
Hi, I love this project it's very cool.

I also get this error:

```
»»» installing/activating WPSeed...
»»» renaming WPSeed to CustomName...
mv: cannot stat 'wp-content/themes/WPSeed-master': No such file or directory
Do you want to continue anyway? (y/n) y
»»» continuing WPDistillery setup...
Error: The 'CustomName' theme could not be found.
Do you want to continue anyway? (y/n) y
»»» continuing WPDistillery setup...
```

I have the default config, only added a rename name:

```
# THEME
#################################################################

# theme to install, choose new name in 'rename' or leave empty
theme:
  name: WPSeed
  rename: "CustomName"
  url: "https://github.com/flurinduerst/WPSeed/archive/master.zip"
  # add branch (e.g. master) or leave empty ("") if theme is not downloaded from a git repository
  source_branch: master
```

@ShaneShipston Is there anything I can do?
@johnpitchko Did you find a solution?

Thank you for your help!
Cheers.
Asael.

**Comment by Matt-Owens** [comment] 2016-11-04 20:39
I'm facing the same problem @johnpitchko Let us know if you found a solution.

**Comment by flurinduerst** [comment] 2016-11-04 20:42
EDIT: Fixed, see my comment below

Hi @johnpitchko, @realnerdo, @Matt-Owens thanks for submitting this issue. It looks like there's a bug in the setup when installing the theme (with or without renaming it, as it looks like).

For now, you can run the setup without cleaning-up (deleting) the default themes, and without installing the "new" theme using the following configuration at `# WPDISTILLERY SETUP` at the bottom of `config.yml` starting at line 100 (changed `theme` and `cleanup_themes` to `false` to bypass the bug):

```
setup:
  wp: true
  settings: true
  theme: false
  plugins: true
  cleanup: true
    comment: true
    posts: true
    files: true
    themes: false
```

Let me know if this temporary workaround works for you, **I will fix this asap**.

**Comment by realnerdo** [comment] 2016-11-04 20:48
@flurinduerst Thank you!

**Comment by Matt-Owens** [comment] 2016-11-04 20:55
@flurinduerst  That fix doesn't work for me -- still timing out.  It might be worth noting I JUST installed most recent version of vagrant (1.8.6). 

Did it work for you @realnerdo ?

**Comment by realnerdo** [comment] 2016-11-04 21:02
@Matt-Owens No, but I'm not getting a timed out error, just the "theme installation" one.

Silly question but did you add your `customdomain.dev` domain to your hosts file?

Also, what happens if you access with the IP? I guess the default for the scotchbox is `192.168.33.10`

Also in my Vagrantfile I have `config.vm.hostname = "customdomain.dev"`

Cheers.

**Comment by Matt-Owens** [comment] 2016-11-07 15:01
@realnerdo I'm just trying to access with the IP -- haven't gone as far as using a domain.

**Comment by vbroskas** [comment] 2016-11-11 22:13
Just to chime in here, I'm having a similar problem. After following the steps, and making minor changes to the config.yml (only changed the email, first_name, last_name.....let everything else at the default settings), when I finally ran  `bash setup.sh`, the only error I received was:

`mv: cannot stat 'wp-content/themes/WPSeed-master': No such file or directory` 

![sb error 1](https://cloud.githubusercontent.com/assets/15919760/20231664/c8d622f6-a820-11e6-9c0d-cb6cbc16ab78.JPG)

Then when I try to access the project via http://192.168.33.10/, it just tells me:

"This site cannot be reached"

I'm going to try what @flurinduerst said about making theme & themes 'false' in the config.yml setup. But I'm curious, wouldn't doing that prevent us from having access to any kind of theme, or installing any themes?

Thanks for the help!

**Comment by vbroskas** [comment] 2016-11-11 23:05
Ok, so I just tried the method where we set theme and themes to 'false' in the config.yml setup section. When I ran `bash setup.sh` installation went smoothly, no errors, all success. However, when I try and access the project via http://192.168.33.10/ (URL: http://wpdistillery.dev/) I get this error:

![sb error 2](https://cloud.githubusercontent.com/assets/15919760/20232849/60031c72-a828-11e6-8ffa-9b7374133967.JPG)

![sb error 3](https://cloud.githubusercontent.com/assets/15919760/20232857/70ba61d8-a828-11e6-9741-1c13370ace2c.JPG)

@realnerdo  & @Matt-Owens , did you guys have any success with this problem?

**Comment by flurinduerst** [comment] 2016-11-15 13:57
Hi guys, thanks a lot for contributing. 

We've got three different problems in this issue:

**1 - Error during theme installation (FIXED)**

```
»»» installing/activating WPSeed...
mv: cannot stat ‘wp-content/themes/WPSeed-master’: No such file or directory
Do you want to continue anyway? (y/n) y
»»» continuing WPDistillery setup...
```

Fixed! (8c798b127e131964036be8633bac85e3cae8f5d9)
Download the newest version, and the theme installation should work without problems again! 
The reason for this was, that since WP-CLI 0.25.0, WP-CLI now also does rename Github themes to remove the branch (in this case "master") from the downloaded theme. WPDistillery did exactly this too. Now, since that is covered by WP-CLI, I removed it from WPDistillery.

---

**2 - Connection refused when installing wordpress (FIXED)**

```
»»» installing wordpress...
/home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 1025 (Errno::ECONNREFUSED)
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `open'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:541:in `tcp_socket'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:551:in `block in do_start'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `call'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:550:in `do_start'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mail-2.6.3/lib/mail/message.rb:238:in `deliver'
    from /home/vagrant/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mailcatcher-0.6.1/bin/catchmail:71:in `<top (required)>'
    from /home/vagrant/.rbenv/versions/2.2.2/bin/catchmail:23:in `load'
    from /home/vagrant/.rbenv/versions/2.2.2/bin/catchmail:23:in `<main>'
Success: WordPress installed successfully.
Success: Updated user 1.
```

Fixed! (db2b58764de2d458a153abb755dcabbad42bcd3c)
Thanks at @ShaneShipston for your suggestion to add `--skip-email`

---

**3 - Not being able to access the page (Needs clarification/bugix/can't reproduce)**

```
When attempting to load wpdistillery.dev, received the following Google error: ERR_CONNECTION_TIMED_OUT
```

As it looks, not everyone is getting this problem. @realnerdo can connect to the local IP/Domain and only got the (now fixed) bug when installing the theme.

Everyone with this connection error (@johnpitchko, @vbroskas, @Matt-Owens): What does your Vagrantfile look like? Did you check your hostfile for any other entries with that IP? 

Note: To be able to access the website via wpdistillery.dev (or whatever you choose) you need to use https://github.com/cogitatio/vagrant-hostsupdater and add the following to the `Vagrantfile`:
`config.vm.hostname = "wpdistillery.dev"`

I will add this info to the readme with a future update asap.

**Comment by johnpitchko** [comment] 2016-11-17 04:51
@flurinduerst here is my Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

end
```

I recall resolving this a few weeks ago. Had something to do with changing the URL in the config.yml file. However I can't remember exactly what I did, was I able to duplicate the resolution tonight.

In the repo, can you just change the config.yml to use the standard URL (192.168.33.10) rather than the wpdistillery.dev hostname?

**Comment by dnspnjrs** [comment] 2016-11-24 16:31
I'm also having issues with the basic setup. Cant connect to the standard ip or to wpdistillery.dev ( get the same timeout message )

During installation i get this warning:
`Warning: cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104`

I'm on OS X 10.11.6

I hope you find a solution!

Edit:

**What worked for me was the following:**
- Setting the correct hostname:
`config.vm.hostname = "wpdistillery.dev"`
- Changing the theme setting to _false_
- Also i forgot to change the _wpsettings:  url_ to the correct url `wpdistillery.dev`

Now it seems to be working fine!

**Comment by flurinduerst** [comment] 2016-12-09 07:57
@dnspnjrs nice to hear that it works now. 

> Also i forgot to change the wpsettings: url to the correct url wpdistillery.dev

This is the default value. But I will add a note to the Readme, that you have to add the hostname to the vagrantfile, if you want to access your project via url rather than via IP.

-------

@johnpitchko 
> In the repo, can you just change the config.yml to use the standard URL (192.168.33.10) rather than the wpdistillery.dev hostname?

I think using a domain rather then an IP to access the project should be the preferred option. As long as `config.vm.hostname` in your Vagrantfile and `wpsettings: url` in config.yml are the same, there shouldn't be any problems. Have you been able to access your project that way?

**Comment by johnpitchko** [comment] 2016-12-09 21:57
Hi @flurinduerst, so I managed to have some success by setting both `config.vm.hostname` in Vagrantfile and `wpsettings url` in config.yml to `scotchbox`. However when I set both these fields to `wpdistillery.dev`, the site times out in my web browser. *note* I do not have _vagrant-hostsupdater_ installed.

So the problem is two fold, if my understanding is correct (which I won't claim is because I am not a smart man):
1. The instructions provided in the readme make no reference to _vagrant-hostsupdater_.
2. The default config.yml is set to `wpsettings url: wpdistillery`, which means that a default install of wpdistillery on a clean install of scotchbox will not work.

If those two issues are present, then there are two solutions:
1. Add an instruction to step 2 of your *Setup* to tell users to verify the hostnames are the same in both `config.yml` and `Vagrantfile`
2. Set the default hostname in `config.yml` to `scotcbox` so users can use the tool on a clean install.

What do others think?

PS very excited to use this!

**Comment by flurinduerst** [comment] 2016-12-20 21:45
> If those two issues are present, then there are two solutions:
>
>1. Add an instruction to step 2 of your Setup to tell users to verify the hostnames are the same in both config.yml and Vagrantfile

In the next major version, I will add a custom Vagrantfile designed for WPDistillery. This will fix the issue that occurred in your and other installation processes posted here. Also it will bring a lot of new features like updating WordPress/Plugins via provisioning etc.

V 2.0 is near 😇

**Closed as completed by flurinduerst** 2016-12-20 21:45 UTC
Labels: bug, high-priority

**Comment by mawiswiss** [comment] 2016-12-20 22:14
Great. Do you also fix some more issues like the following in the new vagrantfile?

To fix a performance problem with VirtualBox, I always add these lines:
```
# Enable NFS because of performance - blame VirtualBox
    config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }
```

Second, I increase the upload file size:
```
# Increase upload file size
config.vm.provision "shell", inline: <<-SHELL
    echo 'echo "upload_max_filesize = 16M" >> /etc/php5/apache2/conf.d/user.ini' | sudo -s
    echo 'echo "post_max_size = 16M" >> /etc/php5/apache2/conf.d/user.ini' | sudo -s
    sudo service apache2 restart
SHELL
```

**Comment by flurinduerst** [comment] 2016-12-20 22:17
the increase in upload file size is already in my dev environment. Can you give me some more insight regarding the performance problem with VirtualBox?

**Comment by mawiswiss** [comment] 2016-12-20 22:58
Ah fine, I wasn't aware of this.

Yes, sure. By default there's one line commented out in the original scotch box vagrantfile. This one points exactly to the problem.

Two links which describes the issue:
https://github.com/scotch-io/scotch-box/issues/144
https://stefanwrobel.com/how-to-make-vagrant-performance-not-suck

**Comment by johnpitchko** [comment] 2016-12-22 22:47
Thanks @flurinduerst I really enjoy using Distillery.

**Comment by gitressa** [comment] 2017-05-22 20:44
The `.dev` suffix has been reserved: https://stackoverflow.com/questions/31216990/icann-name-collision-chrome
So perhaps use `.local` in stead? I just installed a fresh Wordpress with `config.vm.hostname = "wp.local"` in Vagrantfile and `--skip-email` in my `wp core install` command, and everything worked fine.
